### PR TITLE
emacs.sexy icon support

### PR DESCRIPTION
**Pull request by avelino**
`--with-sexy-icon`

ref: #45

### CODE REVIEW

**Comment by natecox** [comment]
Would love to get this merged in; is there anything blocking?

**Comment by evxn** [comment]
@natecox you can fork this repo and install from your own tap:  `brew tap github_username/emacsmacport`

**Comment by avelino** [comment]
@railwaycat check pls

**Comment by railwaycat** [comment]
Sorry for the long waiting and thanks @avelino!

**Pull request merged**
