### PR TITLE
Update to emacs-25.2-rc2-mac-6.2

### PR DESCRIPTION
**Pull request by MerelyAPseudonym**

### CODE REVIEW

**Comment by railwaycat** [comment]
I'm not sure to make this update or not. Version `emacs-25.2-rc2-mac-6.2` never been announced by Mr. Yamamoto on emacs-devel mailing list -- where usually new version been introduced. 

And users can install `25.2-rc2` based mac port by `--HEAD` at any time. The `work` branch is 25.2-rc2 based.

**Comment by MerelyAPseudonym** [comment]
@railwaycat I was not aware that this version hadn’t been announced. I can understand why you’d be hesitant to make the change! Well, I was just trying to be helpful, so I’ll take no offense if you want to close this PR.

**Comment by MerelyAPseudonym** [comment]
Actually, one option would be to put this `emacs-25.2-rc2-mac-6.2` version in a `devel` block. Does that sound like a good idea to you?

**Comment by railwaycat** [comment]
Sounds a good idea, let me take a look. Thanks!

**Pull request closed without merging**
