### PR TITLE
Update option `native-comp` to `native-compilation`

### PR DESCRIPTION
**Pull request by manuraj17**
**Changes**
Update build flag from `native-comp` to `native-compilation`.
Saw it in discussion here #296.

**Notes**
Seemed like a trivial change and felt the authors were welcome about it, hence added these.
Do point out if the scope of changes are much higher; Haven't worked with brew formulae much before. 

**Queries**
1. How should I be actually testing this?

### CODE REVIEW

**Review by avelino — APPROVED** [review]
LGTM

**Comment by manuraj17** [comment]
@avelino FYI: I don't have merge access.

**Comment by avelino** [comment]
> @avelino FYI: I don't have merge access.

I'm not a project maintainer, I do not have approval permission

**Comment by railwaycat** [comment]
Hi @manuraj17, sorry for the delay and thank you for PR. This change looks good to me, however there is one problem: if a user installed emacs-mac with `--with-native-comp`, when this user do a re-install or upgrade to future new version, brew formula will not able to recognize the previous build options since it is no longer exist. The new install will be without native compilation.

Since there is no new version between previous change and this PR, I feel is is safe we merge this PR and fix the above issue later.

**Pull request merged**
