### PR TITLE
fix logic to download icon specified by option

### PR DESCRIPTION
**Pull request by KushNee**
Now the options for icon (e.g: with-gnu-head-icon) are useless because of the code in Line 144: `next if build.without? icon`, Which means `skip download icon when we have an option --without-[icon]`. 

But I think the correct logic is: `download the specified icon in the option --with-[icon], and skip other icons`. The function `build.without` and `build.with` are independent for different prefix.

### CODE REVIEW

**Comment by railwaycat** [comment]
Hi @KushNee, I agree with you for the great finding, thanks! The Homebrew formula cookbook https://docs.brew.sh/Formula-Cookbook#adding-optional-steps verified this behavior too. I think I should accept this PR.

But I'm confused the current code still works: all icon options be recognized on installation.  I can't tell the reason, could be the unknown behavior from Homebrew code.

**Comment by railwaycat** [comment]
```
  41   def without?(val)
  42     !with?(val)
  43   end
```
From `build_options.rb` :)

**Comment by KushNee** [comment]
I checked  the `build_options.rb` and think the Hombrew code is just ok but a little confused.

`without?` function is trying to find an arg which prefixed by `--without-`. So, when you use `if build.without? icon`, not means judging if there is an arg which is `--with-icon`, but finding out if there is an arg named `--without-icon`.

And there is no this argument, so `rm` statement and `install` statement(yes, statements below next) will be invoked.

That is why i say, line 144 is useless.

**Comment by KushNee** [comment]
> ```
>   41   def without?(val)
>   42     !with?(val)
>   43   end
> ```
> 
> From `build_options.rb` :)

Hi @railwaycat, I checked the build_options.rb and think the Hombrew code is just ok but a little confused.

without? function is trying to find an arg which prefixed by --without-. So, when you use if build.without? icon, not means judging if there is an arg which is --with-icon, but finding out if there is an arg named --without-icon.

And there is no this argument, so rm statement and install statement(yes, statements below next) will be invoked.

That is why i say, line 144 is useless.

**Comment by KushNee** [comment]
Hi @railwaycat, I checked the build_options.rb and think the Hombrew code is just ok but a little confused.

`without?` function is trying to find an arg which prefixed by `--without-`. So, when you use `if build.without? icon`, not means judging if there is an arg which is `--with-icon`, but finding out if there is an arg named `--without-icon`.

And there is no this argument, so `rm` statement and `install` statement(yes, statements below next) will be invoked.

That is why i say, line 144 is useless.

**Comment by railwaycat** [comment]
I think the document for options with and without is just as your statement, `build.with?` checks `--with-foo` and `build.without?` checks `--without-foo`. However when Homebrew code implements this feature, it chose a simplified way:
 1. implement `build.with?` to check if `--with-foo` exists or `--without-foo` not exists. 
 2. treat `build.without?` as a negative cast of 1.

This logic you can find in https://github.com/Homebrew/brew/blob/master/Library/Homebrew/build_options.rb between line 14 and line 43. This is my understanding from source code. 

So in practice, `--without-foo` is the same as not state `--with-foo`. Although this is not consistent with formula cookbook. 

This is the reason the old code (before this PR be merged) still works and line 144 is not useless. (but yes, it's confusing).

**Pull request merged**
