### PR TITLE
Add native JSON option

### PR DESCRIPTION
**Pull request by maciej-szlosarczyk**
Adds `--with-json` which install libjansson and passes the the same flag to configure.

### CODE REVIEW

**Comment by pkryger** [comment]
I can see that @railwaycat [has removed this option very recently](https://github.com/railwaycat/homebrew-emacsmacport/commit/ef63d02af94339cf2c2bbd42ea05113809e301fc). I noticed, since I build with `--HEAD` and I used to pass it, and today morning it complained.

However:
- when I build  `--HEAD` via this formulae it doesn't detect my `jansson` library (installed via `brew`). If I hack the formulae and add `--with-janssonn` it finds my `jansson` library.
- when I run configure on a fresh clone from [Mitsuharu's repository](https://bitbucket.org/mituharu/emacs-mac/src/master/) the `configure` called without `--with-jansson` flag is finding my `jansson`. This happens on either `master` or `work` branch.

I haven't been able to get to the bottom of it yet 🤔, but this PR seems to be filling the stop gap.

**Comment by nossralf** [comment]
It appears that Homebrew explicitly sets `PKG_CONFIG_PATH` in the package install shell session based on the `depends_on` dependencies in the formula, so as long as Jansson is not a dependency of the formula, the build will never find it and Emacs will be built without JSON support. This is at least what I've observed when running `brew install --debug` and Ctrl-C:ing to print environment variables in the debug shell.

When building the emacs-mac repository separate from Homebrew, `PKG_CONFIG_PATH` will include *all* installed Homebrew packages that have a pkg-config .pc file, which will include Jansson, which is why it's found there (the `--with-json` flag is default on in Emacs 27.1 so it's found even).

I think the best solution for end users would be to just add Jansson as a `depends_on` and not add any `--with-json` flags, since that would mean everyone will benefit from vastly improved JSON performance with the sole price being having Jansson installed (which uses 196 kB of disk space).

**Comment by pkryger** [comment]
I've just checked with my hacked formulae. Just adding `jansson` to `depends_on` fixes the issue. Thank you @nossralf!

**Comment by maciej-szlosarczyk** [comment]
I admit I haven't put too much thought into it, just noticed it was missing, so it might need to be reworked.

@nossralf might be correct about adding as default dependency, it does not seem like having jansson installed conflicts with anything.

**Comment by eddieh** [comment]
All it needs is the `depends_on`. Both emacs-mac and upstream Emacs build with Jansson by default if it is available. Native support for JSON was the main reason I updated to 27.1 and it was one of the major feature of the release.

Can we get an updated pull request with just the `depends_on`? Is there anything that needs to be done to update the casks too?

**Comment by railwaycat** [comment]
It looks `pkg-config` picks up jansson library if jansson is installed, whatever if `--with-json` is included or not for configure. The only possible is to explicitly exclude jansson by `--without-json`. 

This behavior is different from options like libxml2. I don't know the reason why they made this decision.

**Comment by railwaycat** [comment]
I agree with @nossralf to build with json support by default, and let the formula has a `--without-json` option for people with the needs to opt-out this dependency. 

The same behavior could apply to `--with-libxml2` and `--with-modules` too.

**Comment by railwaycat** [comment]
Hi @maciej-szlosarczyk, I created a new branch `options-cleanup` and going to merge this PR to the new branch. Then apply the changes I mentioned above for libxml2 and modules options. To minimize the impact for users.

**Comment by maciej-szlosarczyk** [comment]
Hey @railwaycat, I made the changes you described earlier, check if this is what the behaviour you wanted. I checked that both `--without-jansson` and `--without-libxml2` switches work as expected.

**Comment by railwaycat** [comment]
Excellent @maciej-szlosarczyk, that's exactly we talked above!

**Pull request merged**
